// Script to update boss data with correct names from current mod versions
import fs from "fs"

const updatedBosses = [
    // Vanilla bosses - unchanged
    {
        id: 1,
        name: "King Slime",
        mod: "vanilla",
        health: 2000,
        defense: 10,
        progression: "pre-hardmode",
        order: 1,
    },
    {
        id: 2,
        name: "Eye of Cthulhu",
        mod: "vanilla",
        health: 2800,
        defense: 12,
        progression: "pre-hardmode",
        order: 2,
    },
    {
        id: 3,
        name: "Brain of Cthulhu",
        mod: "vanilla",
        health: 1000,
        defense: 14,
        progression: "pre-hardmode",
        order: 3,
    },
    {
        id: 4,
        name: "Eater of Worlds",
        mod: "vanilla",
        health: 7325,
        defense: 2,
        progression: "pre-hardmode",
        order: 3,
    },
    {
        id: 5,
        name: "Queen Bee",
        mod: "vanilla",
        health: 3400,
        defense: 8,
        progression: "pre-hardmode",
        order: 4,
    },
    {
        id: 6,
        name: "Skeletron",
        mod: "vanilla",
        health: 4400,
        defense: 10,
        progression: "pre-hardmode",
        order: 5,
    },
    {
        id: 7,
        name: "Deerclops",
        mod: "vanilla",
        health: 7000,
        defense: 10,
        progression: "pre-hardmode",
        order: 6,
    },
    {
        id: 8,
        name: "Wall of Flesh",
        mod: "vanilla",
        health: 8000,
        defense: 12,
        progression: "pre-hardmode",
        order: 7,
    },
    {
        id: 9,
        name: "Queen Slime",
        mod: "vanilla",
        health: 18000,
        defense: 12,
        progression: "hardmode",
        order: 8,
    },
    {
        id: 10,
        name: "The Twins",
        mod: "vanilla",
        health: 40000,
        defense: 20,
        progression: "hardmode",
        order: 9,
    },
    {
        id: 11,
        name: "The Destroyer",
        mod: "vanilla",
        health: 80000,
        defense: 0,
        progression: "hardmode",
        order: 9,
    },
    {
        id: 12,
        name: "Skeletron Prime",
        mod: "vanilla",
        health: 59000,
        defense: 30,
        progression: "hardmode",
        order: 9,
    },
    {
        id: 13,
        name: "Plantera",
        mod: "vanilla",
        health: 50000,
        defense: 36,
        progression: "post-plantera",
        order: 10,
    },
    {
        id: 14,
        name: "Golem",
        mod: "vanilla",
        health: 46000,
        defense: 32,
        progression: "post-golem",
        order: 11,
    },
    {
        id: 15,
        name: "Duke Fishron",
        mod: "vanilla",
        health: 50000,
        defense: 50,
        progression: "post-plantera",
        order: 12,
    },
    {
        id: 16,
        name: "Empress of Light",
        mod: "vanilla",
        health: 70000,
        defense: 50,
        progression: "post-plantera",
        order: 13,
    },
    {
        id: 17,
        name: "Lunatic Cultist",
        mod: "vanilla",
        health: 32000,
        defense: 42,
        progression: "post-golem",
        order: 14,
    },
    {
        id: 18,
        name: "Moon Lord",
        mod: "vanilla",
        health: 145000,
        defense: 70,
        progression: "post-moon-lord",
        order: 15,
    },
    // Calamity bosses - updated names and order
    {
        id: 1,
        name: "Giant Clam",
        mod: "calamity",
        health: 1500,
        defense: 5,
        progression: "pre-hardmode",
        order: 1,
    },
    {
        id: 2,
        name: "Desert Scourge",
        mod: "calamity",
        health: 7200,
        defense: 4,
        progression: "pre-hardmode",
        order: 2,
    },
    {
        id: 3,
        name: "Crabulon",
        mod: "calamity",
        health: 14500,
        defense: 8,
        progression: "pre-hardmode",
        order: 3,
    },
    {
        id: 4,
        name: "The Hive Mind",
        mod: "calamity",
        health: 21000,
        defense: 10,
        progression: "pre-hardmode",
        order: 4,
    },
    {
        id: 5,
        name: "The Perforators",
        mod: "calamity",
        health: 22500,
        defense: 10,
        progression: "pre-hardmode",
        order: 4,
    },
    {
        id: 6,
        name: "The Slime God",
        mod: "calamity",
        health: 45000,
        defense: 20,
        progression: "pre-hardmode",
        order: 5,
    },
    {
        id: 7,
        name: "Cryogen",
        mod: "calamity",
        health: 82000,
        defense: 20,
        progression: "hardmode",
        order: 6,
    },
    {
        id: 8,
        name: "Aquatic Scourge",
        mod: "calamity",
        health: 120000,
        defense: 28,
        progression: "hardmode",
        order: 7,
    },
    {
        id: 9,
        name: "Brimstone Elemental",
        mod: "calamity",
        health: 160000,
        defense: 30,
        progression: "hardmode",
        order: 8,
    },
    {
        id: 10,
        name: "Calamitas Clone",
        mod: "calamity",
        health: 190000,
        defense: 35,
        progression: "hardmode",
        order: 9,
    },
    {
        id: 11,
        name: "Leviathan and Anahita",
        mod: "calamity",
        health: 250000,
        defense: 40,
        progression: "post-plantera",
        order: 10,
    },
    {
        id: 12,
        name: "Astrum Aureus",
        mod: "calamity",
        health: 300000,
        defense: 45,
        progression: "post-plantera",
        order: 11,
    },
    {
        id: 13,
        name: "The Plaguebringer Goliath",
        mod: "calamity",
        health: 350000,
        defense: 50,
        progression: "post-plantera",
        order: 12,
    },
    {
        id: 14,
        name: "Ravager",
        mod: "calamity",
        health: 400000,
        defense: 55,
        progression: "post-golem",
        order: 13,
    },
    {
        id: 15,
        name: "Astrum Deus",
        mod: "calamity",
        health: 600000,
        defense: 60,
        progression: "post-golem",
        order: 14,
    },
    {
        id: 16,
        name: "Profaned Guardians",
        mod: "calamity",
        health: 700000,
        defense: 65,
        progression: "post-moon-lord",
        order: 15,
    },
    {
        id: 17,
        name: "Dragonfolly",
        mod: "calamity",
        health: 800000,
        defense: 70,
        progression: "post-moon-lord",
        order: 16,
    },
    {
        id: 18,
        name: "Providence, the Profaned Goddess",
        mod: "calamity",
        health: 1200000,
        defense: 80,
        progression: "post-moon-lord",
        order: 17,
    },
    {
        id: 19,
        name: "Storm Weaver",
        mod: "calamity",
        health: 1600000,
        defense: 85,
        progression: "post-moon-lord",
        order: 18,
    },
    {
        id: 20,
        name: "Ceaseless Void",
        mod: "calamity",
        health: 1400000,
        defense: 85,
        progression: "post-moon-lord",
        order: 18,
    },
    {
        id: 21,
        name: "Signus, Envoy of the Devourer",
        mod: "calamity",
        health: 1800000,
        defense: 85,
        progression: "post-moon-lord",
        order: 18,
    },
    {
        id: 22,
        name: "Polterghast",
        mod: "calamity",
        health: 2000000,
        defense: 90,
        progression: "post-moon-lord",
        order: 19,
    },
    {
        id: 23,
        name: "The Old Duke",
        mod: "calamity",
        health: 2200000,
        defense: 95,
        progression: "post-moon-lord",
        order: 20,
    },
    {
        id: 24,
        name: "The Devourer of Gods",
        mod: "calamity",
        health: 3500000,
        defense: 100,
        progression: "post-moon-lord",
        order: 21,
    },
    {
        id: 25,
        name: "Jungle Dragon, Yharon",
        mod: "calamity",
        health: 5000000,
        defense: 110,
        progression: "post-moon-lord",
        order: 22,
    },
    {
        id: 26,
        name: "Exo Mechs",
        mod: "calamity",
        health: 6000000,
        defense: 120,
        progression: "post-moon-lord",
        order: 23,
    },
    {
        id: 27,
        name: "Supreme Calamitas",
        mod: "calamity",
        health: 8000000,
        defense: 150,
        progression: "post-moon-lord",
        order: 24,
    },
    // Thorium bosses - updated (removed Ragnarok)
    {
        id: 1,
        name: "The Grand Thunder Bird",
        mod: "thorium",
        health: 3200,
        defense: 6,
        progression: "pre-hardmode",
        order: 1,
    },
    {
        id: 2,
        name: "Queen Jellyfish",
        mod: "thorium",
        health: 4000,
        defense: 8,
        progression: "pre-hardmode",
        order: 2,
    },
    {
        id: 3,
        name: "Viscount",
        mod: "thorium",
        health: 4500,
        defense: 10,
        progression: "pre-hardmode",
        order: 3,
    },
    {
        id: 4,
        name: "Granite Energy Storm",
        mod: "thorium",
        health: 5000,
        defense: 12,
        progression: "pre-hardmode",
        order: 4,
    },
    {
        id: 5,
        name: "The Buried Champion",
        mod: "thorium",
        health: 6000,
        defense: 14,
        progression: "pre-hardmode",
        order: 5,
    },
    {
        id: 6,
        name: "The Star Scouter",
        mod: "thorium",
        health: 7500,
        defense: 16,
        progression: "pre-hardmode",
        order: 6,
    },
    {
        id: 7,
        name: "Borean Strider",
        mod: "thorium",
        health: 8500,
        defense: 18,
        progression: "pre-hardmode",
        order: 7,
    },
    {
        id: 8,
        name: "Coznix, The Fallen Beholder",
        mod: "thorium",
        health: 9500,
        defense: 20,
        progression: "pre-hardmode",
        order: 8,
    },
    {
        id: 9,
        name: "The Lich",
        mod: "thorium",
        health: 35000,
        defense: 30,
        progression: "hardmode",
        order: 9,
    },
    {
        id: 10,
        name: "Abyssion, The Forgotten One",
        mod: "thorium",
        health: 75000,
        defense: 40,
        progression: "hardmode",
        order: 10,
    },
    {
        id: 11,
        name: "Primordials",
        mod: "thorium",
        health: 500000,
        defense: 80,
        progression: "post-moon-lord",
        order: 11,
    },
]

console.log("=== Updating Boss Data ===\n")
console.log("Changes:")
console.log("  Calamity:")
console.log("    - Added: Giant Clam (mini-boss)")
console.log("    - Added: Exo Mechs")
console.log("    - Reordered to match current mod progression")
console.log("  Thorium:")
console.log("    - Removed: The Ragnarok (not a real boss)")
console.log("    - Total: 11 bosses\n")

fs.writeFileSync("data/bosses-all.json", JSON.stringify(updatedBosses, null, 2))

console.log("✅ Boss data updated!")
console.log(`Total bosses: ${updatedBosses.length}`)
console.log(
    `  - Vanilla: ${updatedBosses.filter((b) => b.mod === "vanilla").length}`
)
console.log(
    `  - Calamity: ${updatedBosses.filter((b) => b.mod === "calamity").length}`
)
console.log(
    `  - Thorium: ${updatedBosses.filter((b) => b.mod === "thorium").length}`
)
